### ISSUE TITLE
New York 98

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#30]
Currently we do not have the full final standings of that PT, because they are unavailable on will be for the forseeable future. I even asked Rich Hagon about them and he submitted a formal databank lookup request at Wizards, but no success. I would like to add provisional standings for that tournament beyond place 66 anway, and would like what you think about it.

My reasoning?
The top 64 are readily available in the coverage archive. These we have anyway. We also have the standings after day one, because I unearthed them from the webarchives. We also have a handful of individual finishes from individual reports.

Unfortunately back then tiebreakers still changed after a player dropped from the tournament. Thus the day one standings are not the final standings, not even or the players that did not make day two.

After day one there was a cut to top 96. So we know, that the 30 players, that did not finish in the top 66 are places 67-96 in some order. They all received 3 Pro Points and no cash, so their actual placement is not all that important. We do know that place 137+ after day one stayed in place 137+ in the final standings, because they have fewer points than 97-137. 137+ received 2 Pro Point and no cash.

So in the end there are 40 players where we do not exactly know if they received 2 or 3 Pro Points. The tiebkreakers of most of them will not have changed so dramatically to propel them from one category to the other.

What would I like to do exactly?
Add the players in place 67-96 in arbitrary order, and add place 97+ in the order they finished after day one. It is not optimal, but our statistics will be more accurate than they are without this, and I would give an explanation like this on Twitter. Are you okay with this addition?

Sorry if that was a bit long for something that you may consider of minor importance.

**Comment by czarandy** [comment]
Yeah that sounds like a good idea. I agree it's better to have some data even if it's slightly incorrect. 






On Thu, May 19, 2016 at 7:45 AM -0700, "OdinFK" <notifications@github.com> wrote:












Currently we do not have the full final standings of that PT, because they are unavailable on will be for the forseeable future. I even asked Rich Hagon about them and he submitted a formal databank lookup request at Wizards, but no success. I would like to add provisional standings for that tournament beyond place 66 anway, and would like what you think about it.



My reasoning?

The top 64 are readily available in the coverage archive. These we have anyway. We also have the standings after day one, because I unearthed them from the webarchives. We also have a handful of individual finishes from individual reports.



Unfortunately back then tiebreakers still changed after a player dropped from the tournament. Thus the day one standings are not the final standings, not even or the players that did not make day two.



After day one there was a cut to top 96. So we know, that the 30 players, that did not finish in the top 66 are places 67-96 in some order. They all received 3 Pro Points and no cash, so their actual placement is not all that important. We do know that place 137+ after day one stayed in place 137+ in the final standings, because they have fewer points than 97-137. 137+ received 2 Pro Point and no cash.



So in the end there are 40 players where we do not exactly know if they received 2 or 3 Pro Points. The tiebkreakers of most of them will not have changed so dramatically to propel them from one category to the other.



What would I like to do exactly?

Add the players in place 67-96 in arbitrary order, and add place 97+ in the order they finished after day one. It is not optimal, but our statistics will be more accurate than they are without this, and I would give an explanation like this on Twitter. Are you okay with this addition?



Sorry if that was a bit long for something that you may consider of minor importance.
