### ISSUE TITLE
Break up tournaments.json

### ISSUE THREAD

**Issue by czarandy** [czarandy/mtgptresults#9]
This file is too large so it's hard to view any changes to it. I think we can break it up into one file per tournament.

**Comment by OdinFK** [comment]
Can you wait a little with this? I am currently consolidating the player names and that is much more easy with one big file.

Also I do believe that the database is now as complete as it could be (1996 PT results for 65+ finishes are not going to show up in the foreseeable future for example) so I don't foresee many changes other than adding PTs in the future.

**Comment by mlnmln** [comment]
@OdinFK It's hard to review changes and getting a proper `diff` in a file as big as it is now. People may still want to fix wrong player names or make small changes in the future. I could split the file quite easily.

**Comment by mlnmln** [comment]
> Can you wait a little with this? I am currently consolidating the player names and that is much more easy with one big file.

Sorry, missed that line in the first place. I'd suggest making a single commit for each changed player too have smaller chunks. In the future, search and replace over multiple files should be just a easy as single file.

**Comment by OdinFK** [comment]
@mlnmln Isn't that just atrocious for everybody? This way I have to make over 100 commits and you have to check all of them. I know it is not ideal to do everything in one, but considering that there is basically a bunch of noise in the data, and even if I did a few mistakes my update is guaranteed to reduce a lot of that noise, it seems way less annoying to do it this way.

I can include a list of all the changes in my update, though. Maybe that helps if you want to check something?

**Comment by mlnmln** [comment]
> @mlnmln Isn't that just atrocious for everybody? This way I have to make over 100 commits and you have to check all of them. 

Ok. wow, did not realize the scope of your ongoing changes. 

If making so many commits is too cumbersome, then I'd suggest you just make sure that the new JSON files are still valid and keep working as carefully as you already do. 

> I can include a list of all the changes in my update, though. Maybe that helps if you want to check something?

Sure thing :)

**Comment by OdinFK** [comment]
> Ok. wow, did not realize the scope of your ongoing changes.
Yeah, Americans and their fetish for middle initials. Quite annoying...

For reference at the bottom I included the names, that I did not change, because I was not completely sure, if these are different persons or duplicates.

There are a three other specific case, too.

*sebastian aljiaj / sebastian thaler
This is the same person. Sebastian changed his last name at some point. So just change Aljiaj to Thaler everywhere and ignore that Aljiaj ever "existed"?

*rickard osterberg
Osterberg is consistently used, but it should really be Österberg. Was just too lazy.

*neil reeves / richard reeves (and Trey Van Cleave / Richard Van Cleave)
In both case it is not directly obvious that these are the same persons, but as a matter of fact they are. Van Cleave used Richard only in the 90s, so that is not really an issue, but Neil Reeves changed to using Richard relatively recently. People will search for Neil and not find him. It's not the biggest issue, and doesn't need immediate fixing, but I think it is something to keep in mind.



People were I am relatively confident that they are identical, but don't know for sure.
tom guevin / thomas guevin
ben seck / benjamin seck / ben tbs seck
cheung chun lap / lap chung cheung
ryan soh / ryan siong huat soh / siong huat soh
ken fujita / ken’ichi fujita / kenichi fujita
wing lok tam / tam wing lok
pedro alvarado / pe alvarado chavarria
michael sochon / sochon mickael
greg weiss / gregory weiss
nichola wong keen meng / nicholas wong
bo su / bo sun / brian bo su (?)
daniel k gardner / daniel j gardner / daniel gardner

**Comment by mlnmln** [comment]
@czarandy @OdinFK 

I think we should still split up the `tournaments.json` and move the notes from @OdinFK to a separate issue for further reference. Ok?

**Comment by OdinFK** [comment]
This breakup thing still bugs me. Currently working on the files... Will the tournaments.json still exist in its current form?

**Comment by mlnmln** [comment]
@OdinFK 
I won't do anything here without your consent, no worries. 
I thought now that you made two major updates, we could further pursue this issue. 
What would be a good solution for you from an editor's perspective?

**Comment by OdinFK** [comment]
We should just agree on a day on which the split will happen. I will reign myself and not do edits on that day, then.

**Comment by czarandy** [comment]
Ok, I split up tournaments.json:
https://github.com/czarandy/mtgptresults/commit/807450c1c474c1e335b04cc26464e0b7d04174c5

Each tournament just has its own file, so it should be pretty clear how to edit.
If you have a lot of conflicts with other changes you are doing, you can send me your tournaments.json and I can split it up into the relevant changed files.
